### ISSUE TITLE
CI for build/deploy

### ISSUE THREAD

**Issue by tynes** [handshake-org/handshake-org.github.io#81]
It would be really useful to enable automatic builds and deploys in CI when things are merged to master.

An example of using Travis-CI from `bcoin`:
https://github.com/bcoin-org/bcoin-org.github.io/blob/staging/.travis.yml

**Comment by Falci** [comment]
GitHub has now the [Actions](https://github.com/handshake-org/handshake-org.github.io/actions), similar to Travis, but "in house".

I'll have a look on it.

**Comment by Falci** [comment]
Could you please confirm what are the [settings](https://github.com/handshake-org/handshake-org.github.io/settings) for the GitHub Pages section?

Is it like the following?
![image](https://user-images.githubusercontent.com/1330573/106070084-11b88180-6104-11eb-995b-17f6cd2b773d.png)

**Comment by Falci** [comment]
I'd like to suggest a big change here:
1. The build should not generate the over the root folder, but under a specific folder (`/build`?)
2. The GitHub Pages should have the source in another branch (usually `gh-pages`)

Reasons:
1. It would keep the repo clean.
2. We can trigger the build automatically when there's a push/merge to master. So, the build should not change the master branch, otherwise it would cause another auto-build.

**Comment by pinheadmz** [comment]
![Screenshot from 2021-01-29 16-46-18](https://user-images.githubusercontent.com/2084648/106330640-9238c880-6251-11eb-8e21-b9d9ecc819ee.png)
